"""Domain constants for the Assessment bounded context."""

DEFAULT_PASSING_THRESHOLD_PERCENT: float = 80.0
DEFAULT_QUIZ_TIME_LIMIT_MINUTES: int = 45
DEFAULT_QUIZ_EASY_COUNT: int = 4
DEFAULT_QUIZ_MEDIUM_COUNT: int = 4
DEFAULT_QUIZ_HARD_COUNT: int = 2

MAX_QUIZ_ATTEMPTS_BEFORE_COOLDOWN: int = 3
QUIZ_COOLDOWN_HOURS: int = 8
QUIZ_SUBMISSION_GRACE_PERIOD_SECONDS: int = 30

REQUIRED_PEER_REVIEWS_COUNT: int = 3
OUTLIER_SCORE_DELTA_THRESHOLD: float = 30.0
PEER_REVIEW_COLD_START_HOURS: int = 48

DEFAULT_SANDBOX_TIMEOUT_SECONDS: float = 5.0
MAX_SANDBOX_TIMEOUT_SECONDS: float = 30.0
DEFAULT_SANDBOX_MEMORY_LIMIT_MB: int = 512
