from enum import Enum


class NotificationCategory(str, Enum):
    UNSPECIFIED = "UNSPECIFIED"
    SYSTEM = "SYSTEM"
    ACADEMIC = "ACADEMIC"
    COMMUNITY = "COMMUNITY"
    ANNOUNCEMENT = "ANNOUNCEMENT"


DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
TITLE_MAX_LENGTH = 150
CONTENT_MAX_LENGTH = 1000
ACTION_URL_MAX_LENGTH = 500
RETENTION_DAYS = 90
