"""Domain constants for Payment & Subscription Bounded Context (BR_ACCESS_004)."""

DEFAULT_MONTHLY_PLAN_DAYS = 30
DEFAULT_YEARLY_PLAN_DAYS = 365

DEFAULT_SINGLE_COURSE_PRICE_VND = 1190000.0
DEFAULT_CURRENCY = "VND"
