"""Domain constants for Payment & Subscription Bounded Context (BR_ACCESS_004)."""

DEFAULT_MONTHLY_PLAN_DAYS = 30
DEFAULT_YEARLY_PLAN_DAYS = 365

DEFAULT_SINGLE_COURSE_PRICE_VND = 1190000.0
DEFAULT_SYSTEM_SUBSCRIPTION_MONTHLY_PRICE_VND = 790000.0
DEFAULT_SYSTEM_SUBSCRIPTION_YEARLY_PRICE_VND = 5900000.0
DEFAULT_CURRENCY = "VND"

PENDING_ORDER_REUSE_TTL_MINUTES = 15
RECONCILIATION_PENDING_WINDOW_MINUTES = 15
RECONCILIATION_BATCH_SIZE = 50
