"""add_prohibit_seeking_to_learning_item

Revision ID: 04766e42c415
Revises: 44e5fc5daf08
Create Date: 2026-07-26 02:24:41.791197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04766e42c415"
down_revision: Union[str, Sequence[str], None] = "44e5fc5daf08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_items",
        sa.Column(
            "prohibit_seeking", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learning_items", "prohibit_seeking")
    # ### end Alembic commands ###
