"""add_unique_constraints_and_foreign_keys

Revision ID: 0ca87f0df402
Revises: 8a82cf9d3dd3
Create Date: 2026-08-08 00:53:18.492038

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ca87f0df402"
down_revision: str | Sequence[str] | None = "8a82cf9d3dd3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_financial_aid_user_course",
        "financial_aid_applications",
        ["user_id", "course_id"],
    )
    op.create_unique_constraint(
        "uq_grade_appeal_user_submission", "grade_appeals", ["user_id", "submission_id"]
    )
    op.create_unique_constraint(
        "uq_org_member_org_user", "organization_members", ["organization_id", "user_id"]
    )
    op.create_foreign_key(
        op.f("payment_transactions_order_id_fkey"),
        "payment_transactions",
        "payment_orders",
        ["order_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "uq_peer_submission_user_item",
        "peer_assignment_submissions",
        ["user_id", "item_id"],
    )
    op.create_unique_constraint(
        "uq_peer_review_submission_reviewer",
        "peer_reviews",
        ["submission_id", "reviewer_user_id"],
    )
    op.create_unique_constraint(
        "uq_certificate_user_course", "verified_certificates", ["user_id", "course_id"]
    )
    op.create_unique_constraint(
        "uq_weekly_deadline_progress_week",
        "weekly_deadlines",
        ["progress_id", "week_number"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_weekly_deadline_progress_week", "weekly_deadlines", type_="unique"
    )
    op.drop_constraint(
        "uq_certificate_user_course", "verified_certificates", type_="unique"
    )
    op.drop_constraint(
        "uq_peer_review_submission_reviewer", "peer_reviews", type_="unique"
    )
    op.drop_constraint(
        "uq_peer_submission_user_item", "peer_assignment_submissions", type_="unique"
    )
    op.drop_constraint(
        op.f("payment_transactions_order_id_fkey"),
        "payment_transactions",
        type_="foreignkey",
    )
    op.drop_constraint("uq_org_member_org_user", "organization_members", type_="unique")
    op.drop_constraint(
        "uq_grade_appeal_user_submission", "grade_appeals", type_="unique"
    )
    op.drop_constraint(
        "uq_financial_aid_user_course", "financial_aid_applications", type_="unique"
    )
    # ### end Alembic commands ###
