"""add seat_assigned_at to users

Revision ID: 10ba27276f02
Revises: a7e8910b2c3d
Create Date: 2026-07-24 14:06:44.963716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10ba27276f02"
down_revision: Union[str, Sequence[str], None] = "a7e8910b2c3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("uq_forum_user_post_vote"), table_name="forum_votes")
    op.create_unique_constraint(
        "uq_forum_user_post_vote", "forum_votes", ["user_id", "post_id"]
    )
    op.add_column(
        "peer_assignment_submissions",
        sa.Column("final_score", sa.Float(), nullable=True),
    )
    op.add_column(
        "peer_assignment_submissions",
        sa.Column(
            "graded_by_staff", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column("users", sa.Column("seat_assigned_at", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "seat_assigned_at")
    op.drop_column("peer_assignment_submissions", "graded_by_staff")
    op.drop_column("peer_assignment_submissions", "final_score")
    op.drop_constraint("uq_forum_user_post_vote", "forum_votes", type_="unique")
    op.create_index(
        op.f("uq_forum_user_post_vote"),
        "forum_votes",
        ["user_id", "post_id"],
        unique=True,
    )
    # ### end Alembic commands ###
