"""add_scorm_support

Revision ID: 2f5d70a67569
Revises: 7a8f9e1029ab
Create Date: 2026-07-25 10:57:01.159832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f5d70a67569"
down_revision: Union[str, Sequence[str], None] = "7a8f9e1029ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scorm_trackings",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("cmi_data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scorm_trackings_item_id"), "scorm_trackings", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_scorm_trackings_user_id"), "scorm_trackings", ["user_id"], unique=False
    )
    op.add_column(
        "learning_items",
        sa.Column(
            "scorm_package_path",
            sa.String(length=512),
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "learning_items",
        sa.Column(
            "scorm_entry_html", sa.String(length=255), nullable=False, server_default=""
        ),
    )

    # Add 'SCORM' to itemtype enum
    op.execute("COMMIT")
    op.execute("ALTER TYPE itemtype ADD VALUE 'SCORM'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learning_items", "scorm_entry_html")
    op.drop_column("learning_items", "scorm_package_path")
    op.drop_index(op.f("ix_scorm_trackings_user_id"), table_name="scorm_trackings")
    op.drop_index(op.f("ix_scorm_trackings_item_id"), table_name="scorm_trackings")
    op.drop_table("scorm_trackings")
    # ### end Alembic commands ###
