"""standardize forum id column lengths to String(64)

Revision ID: 38e60e429f76
Revises: dd8170ce953d
Create Date: 2026-07-24 14:37:08.775037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38e60e429f76"
down_revision: Union[str, Sequence[str], None] = "dd8170ce953d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "forum_replies",
        "id",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "forum_replies",
        "thread_id",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "forum_threads",
        "id",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "forum_votes",
        "id",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "forum_votes",
        "post_id",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "forum_votes",
        "post_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "forum_votes",
        "id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "forum_threads",
        "id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "forum_replies",
        "thread_id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "forum_replies",
        "id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
