"""remove_organization_roles_table_and_fk

Revision ID: 3ad4b17a9418
Revises: aaafb085b524
Create Date: 2026-08-03 05:12:46.166513

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ad4b17a9418"
down_revision: str | Sequence[str] | None = "aaafb085b524"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("organization_members_role_id_fkey"),
        "organization_members",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_organization_roles_organization_id"), table_name="organization_roles"
    )
    op.drop_table("organization_roles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("organization_members_role_id_fkey"),
        "organization_members",
        "organization_roles",
        ["role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "organization_roles",
        sa.Column("id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "organization_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "parent_role_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("organization_roles_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_role_id"],
            ["organization_roles.id"],
            name=op.f("organization_roles_parent_role_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("organization_roles_pkey")),
    )
    op.create_index(
        op.f("ix_organization_roles_organization_id"),
        "organization_roles",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###
