"""add quiz session snapshots

Revision ID: 3b52b619e02b
Revises: d510ee603d61
Create Date: 2026-07-28 10:58:09.140745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b52b619e02b"
down_revision: Union[str, Sequence[str], None] = "d510ee603d61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_banks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_banks_course_id"),
        "question_banks",
        ["course_id"],
        unique=False,
    )
    op.create_table(
        "quiz_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("questions_json", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.String(length=64), nullable=False),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=False),
        sa.Column("passing_threshold_percent", sa.Float(), nullable=False),
        sa.Column("submitted_at", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_sessions_item_id"), "quiz_sessions", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_sessions_user_id"), "quiz_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("bank_id", sa.String(length=64), nullable=False),
        sa.Column("question_type", sa.String(length=32), nullable=False),
        sa.Column("difficulty", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["bank_id"], ["question_banks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_bank_id"), "questions", ["bank_id"], unique=False
    )
    op.create_table(
        "quiz_matrices",
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("bank_id", sa.String(length=64), nullable=False),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=False),
        sa.Column("passing_threshold_percent", sa.Float(), nullable=False),
        sa.Column("easy_count", sa.Integer(), nullable=False),
        sa.Column("medium_count", sa.Integer(), nullable=False),
        sa.Column("hard_count", sa.Integer(), nullable=False),
        sa.Column("shuffle_options", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_id"],
            ["question_banks.id"],
        ),
        sa.PrimaryKeyConstraint("item_id"),
    )
    op.create_table(
        "question_options",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("question_id", sa.String(length=64), nullable=False),
        sa.Column("option_text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_options_question_id"),
        "question_options",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_question_options_question_id"), table_name="question_options"
    )
    op.drop_table("question_options")
    op.drop_table("quiz_matrices")
    op.drop_index(op.f("ix_questions_bank_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_quiz_sessions_user_id"), table_name="quiz_sessions")
    op.drop_index(op.f("ix_quiz_sessions_item_id"), table_name="quiz_sessions")
    op.drop_table("quiz_sessions")
    op.drop_index(op.f("ix_question_banks_course_id"), table_name="question_banks")
    op.drop_table("question_banks")
    # ### end Alembic commands ###
