"""create catalog and learning tables

Revision ID: 3ca78cb96417
Revises: 
Create Date: 2026-07-21 18:17:41.849275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca78cb96417'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('partner_name', sa.String(length=128), nullable=False),
    sa.Column('partner_logo_url', sa.String(length=512), nullable=False),
    sa.Column('instructor_names', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('learning_progresses',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('overall_progress_percent', sa.Float(), nullable=False),
    sa.Column('completed_item_ids', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_notes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('highlighted_text', sa.Text(), nullable=False),
    sa.Column('note_comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_notes_course_id'), 'personal_notes', ['course_id'], unique=False)
    op.create_index(op.f('ix_personal_notes_user_id'), 'personal_notes', ['user_id'], unique=False)
    op.create_table('specializations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('partner_name', sa.String(length=128), nullable=False),
    sa.Column('partner_logo_url', sa.String(length=512), nullable=False),
    sa.Column('course_ids', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('week_modules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_deadlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('progress_id', sa.String(length=128), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('UNSPECIFIED', 'ON_TRACK', 'OVERDUE', 'COMPLETED', name='deadlinestatus'), nullable=False),
    sa.ForeignKeyConstraint(['progress_id'], ['learning_progresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('week_module_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['week_module_id'], ['week_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lesson_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('UNSPECIFIED', 'VIDEO', 'READING', 'PRACTICE_QUIZ', 'GRADED_QUIZ', 'AUTO_GRADED_LAB', 'PEER_REVIEW', name='itemtype'), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=False),
    sa.Column('vtt_subtitle_url', sa.String(length=512), nullable=False),
    sa.Column('reading_markdown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('in_video_quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactive_transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interactive_transcripts')
    op.drop_table('in_video_quizzes')
    op.drop_table('learning_items')
    op.drop_table('lessons')
    op.drop_table('weekly_deadlines')
    op.drop_table('week_modules')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_personal_notes_user_id'), table_name='personal_notes')
    op.drop_index(op.f('ix_personal_notes_course_id'), table_name='personal_notes')
    op.drop_table('personal_notes')
    op.drop_table('learning_progresses')
    op.drop_table('courses')
    # ### end Alembic commands ###
