"""add_payment_and_subscription_tables

Revision ID: 401a9bf0e06c
Revises: 6b82ed381ac5
Create Date: 2026-07-29 15:57:25.598660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "401a9bf0e06c"
down_revision: Union[str, Sequence[str], None] = "6b82ed381ac5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column("price", sa.Float(), server_default="1190000.0", nullable=False),
    )
    op.add_column(
        "courses",
        sa.Column(
            "currency", sa.String(length=8), server_default="VND", nullable=False
        ),
    )
    op.add_column(
        "courses",
        sa.Column(
            "is_plus_eligible", sa.Boolean(), server_default="true", nullable=False
        ),
    )

    op.create_table(
        "course_purchases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payment_method", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_purchases_course_id"),
        "course_purchases",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_purchases_user_id"),
        "course_purchases",
        ["user_id"],
        unique=False,
    )

    op.create_table(
        "user_subscriptions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("plan_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("starts_at", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_subscriptions_expires_at"),
        "user_subscriptions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_subscriptions_user_id"),
        "user_subscriptions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_subscriptions_user_id"), table_name="user_subscriptions"
    )
    op.drop_index(
        op.f("ix_user_subscriptions_expires_at"), table_name="user_subscriptions"
    )
    op.drop_table("user_subscriptions")

    op.drop_index(op.f("ix_course_purchases_user_id"), table_name="course_purchases")
    op.drop_index(op.f("ix_course_purchases_course_id"), table_name="course_purchases")
    op.drop_table("course_purchases")

    op.drop_column("courses", "is_plus_eligible")
    op.drop_column("courses", "currency")
    op.drop_column("courses", "price")
    # ### end Alembic commands ###
