"""add_auto_transcribe_to_learning_item

Revision ID: 44e5fc5daf08
Revises: 89ba8fb65b06
Create Date: 2026-07-26 02:07:39.509964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44e5fc5daf08"
down_revision: Union[str, Sequence[str], None] = "89ba8fb65b06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_items",
        sa.Column(
            "auto_transcribe", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learning_items", "auto_transcribe")
    # ### end Alembic commands ###
