"""add_auto_transcribe_to_learning_item

Revision ID: 44e5fc5daf08
Revises: 89ba8fb65b06
Create Date: 2026-07-26 02:07:39.509964

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44e5fc5daf08"
down_revision: str | Sequence[str] | None = "f9caddc81895"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_items",
        sa.Column(
            "auto_transcribe", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learning_items", "auto_transcribe")
    # ### end Alembic commands ###
