"""add_forum_edit_fields

Revision ID: 487286dcef82
Revises: a87b2367f1e6
Create Date: 2026-07-25 17:07:45.742807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "487286dcef82"
down_revision: Union[str, Sequence[str], None] = "a87b2367f1e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "forum_replies",
        sa.Column("is_edited", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "forum_replies",
        sa.Column(
            "edited_at", sa.String(length=100), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "forum_threads",
        sa.Column("is_edited", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "forum_threads",
        sa.Column(
            "edited_at", sa.String(length=100), nullable=False, server_default=""
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forum_threads", "edited_at")
    op.drop_column("forum_threads", "is_edited")
    op.drop_column("forum_replies", "edited_at")
    op.drop_column("forum_replies", "is_edited")
    # ### end Alembic commands ###
