"""add quiz active session table

Revision ID: 5181a248800b
Revises: e8ebc2975d4e
Create Date: 2026-07-29 15:42:19.301914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5181a248800b"
down_revision: Union[str, Sequence[str], None] = "e8ebc2975d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_active_sessions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("session_token", sa.Text(), nullable=False),
        sa.Column("session_seed", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_active_sessions_item_id"),
        "quiz_active_sessions",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_active_sessions_user_id"),
        "quiz_active_sessions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quiz_active_sessions_user_id"), table_name="quiz_active_sessions"
    )
    op.drop_index(
        op.f("ix_quiz_active_sessions_item_id"), table_name="quiz_active_sessions"
    )
    op.drop_table("quiz_active_sessions")
    # ### end Alembic commands ###
