"""add_invitations_table

Revision ID: 541c3fdeb299
Revises: f89a1029c001
Create Date: 2026-08-07 14:42:01.652157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "541c3fdeb299"
down_revision: Union[str, Sequence[str], None] = "f89a1029c001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default="INVITATION_STATUS_PENDING",
            nullable=False,
        ),
        sa.Column("inviter_id", sa.String(length=64), nullable=False),
        sa.Column("inviter_name", sa.String(length=255), nullable=False),
        sa.Column("inviter_email", sa.String(length=255), nullable=False),
        sa.Column("invitee_email", sa.String(length=255), nullable=False),
        sa.Column("invitee_id", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("target_name", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.Column("responded_at", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["invitee_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["inviter_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invitations_invitee_email"),
        "invitations",
        ["invitee_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invitations_invitee_id"), "invitations", ["invitee_id"], unique=False
    )
    op.create_index(
        op.f("ix_invitations_inviter_id"), "invitations", ["inviter_id"], unique=False
    )
    op.create_index(
        op.f("ix_invitations_status"), "invitations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_invitations_target_id"), "invitations", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_invitations_token_hash"), "invitations", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_invitations_type"), "invitations", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invitations_type"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_token_hash"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_target_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_status"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_inviter_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_invitee_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_invitee_email"), table_name="invitations")
    op.drop_table("invitations")
    # ### end Alembic commands ###
