"""add_br_review_002_and_csat_cache

Revision ID: 55863ba0dee5
Revises: fd77c3cd6a9a
Create Date: 2026-07-25 12:48:26.204716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55863ba0dee5"
down_revision: Union[str, Sequence[str], None] = "fd77c3cd6a9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course_reviews",
        sa.Column(
            "is_verified_completer",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "courses",
        sa.Column("average_rating", sa.Float(), server_default="0.0", nullable=False),
    )
    op.add_column(
        "courses",
        sa.Column("review_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "learning_progresses",
        sa.Column("last_reset_at", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learning_progresses", "last_reset_at")
    op.drop_column("courses", "review_count")
    op.drop_column("courses", "average_rating")
    op.drop_column("course_reviews", "is_verified_completer")
    # ### end Alembic commands ###
