"""add_quiz_matrix_attempts_and_cooldown

Revision ID: 5c33582e05dd
Revises: 3b52b619e02b
Create Date: 2026-07-29 15:51:35.332756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c33582e05dd"
down_revision: Union[str, Sequence[str], None] = "3b52b619e02b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_matrices",
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
    )
    op.add_column(
        "quiz_matrices",
        sa.Column("cooldown_hours", sa.Integer(), server_default="8", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz_matrices", "cooldown_hours")
    op.drop_column("quiz_matrices", "max_attempts")
    # ### end Alembic commands ###
