"""add specialization_id to verified_certificates

Revision ID: 685be7ef1e53
Revises: 92c325e689de
Create Date: 2026-07-24 14:17:25.911609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "685be7ef1e53"
down_revision: Union[str, Sequence[str], None] = "92c325e689de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verified_certificates",
        sa.Column("specialization_id", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verified_certificates", "specialization_id")
    # ### end Alembic commands ###
