"""add specialization_id to verified_certificates

Revision ID: 685be7ef1e53
Revises: 92c325e689de
Create Date: 2026-07-24 14:17:25.911609

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "685be7ef1e53"
down_revision: str | Sequence[str] | None = "92c325e689de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verified_certificates",
        sa.Column("specialization_id", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verified_certificates", "specialization_id")
    # ### end Alembic commands ###
