"""add_financial_aid_enabled_to_courses

Revision ID: 6b82ed381ac5
Revises: e8ebc2975d4e
Create Date: 2026-07-29 15:18:33.577145

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b82ed381ac5"
down_revision: str | Sequence[str] | None = "e8ebc2975d4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column(
            "financial_aid_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "financial_aid_enabled")
    # ### end Alembic commands ###
