"""add organization_audit_logs table

Revision ID: 7dbaed96d10a
Revises: 541c3fdeb299
Create Date: 2026-08-08 00:18:41.906359

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7dbaed96d10a"
down_revision: str | Sequence[str] | None = "541c3fdeb299"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_audit_logs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("target_user_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_audit_logs_actor_id"),
        "organization_audit_logs",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_audit_logs_organization_id"),
        "organization_audit_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_audit_logs_target_user_id"),
        "organization_audit_logs",
        ["target_user_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_partner_subscriptions_expires_at"), table_name="partner_subscriptions"
    )
    op.drop_index(
        op.f("ix_partner_subscriptions_partner_id"), table_name="partner_subscriptions"
    )
    op.drop_index(
        op.f("ix_partner_subscriptions_user_id"), table_name="partner_subscriptions"
    )
    op.drop_table("partner_subscriptions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partner_subscriptions",
        sa.Column("id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "user_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "partner_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "plan_type", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("status", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "starts_at", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expires_at", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("partner_subscriptions_pkey")),
    )
    op.create_index(
        op.f("ix_partner_subscriptions_user_id"),
        "partner_subscriptions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partner_subscriptions_partner_id"),
        "partner_subscriptions",
        ["partner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partner_subscriptions_expires_at"),
        "partner_subscriptions",
        ["expires_at"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_organization_audit_logs_target_user_id"),
        table_name="organization_audit_logs",
    )
    op.drop_index(
        op.f("ix_organization_audit_logs_organization_id"),
        table_name="organization_audit_logs",
    )
    op.drop_index(
        op.f("ix_organization_audit_logs_actor_id"),
        table_name="organization_audit_logs",
    )
    op.drop_table("organization_audit_logs")
    # ### end Alembic commands ###
