"""add_scorm_data_to_learning_progresses

Revision ID: 7fbdbeae66dc
Revises: f7b500c09994
Create Date: 2026-07-31 23:38:32.849147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fbdbeae66dc"
down_revision: Union[str, Sequence[str], None] = "f7b500c09994"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_progresses",
        sa.Column("scorm_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("learning_progresses", "scorm_data")
    # ### end Alembic commands ###
