"""refactor_currency_numeric_and_add_indexes

Revision ID: 8a82cf9d3dd3
Revises: e26aefbf2406
Create Date: 2026-08-08 00:43:38.890663

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a82cf9d3dd3"
down_revision: str | Sequence[str] | None = "e26aefbf2406"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "course_purchases",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
        existing_server_default=sa.text("'1190000'::double precision"),
    )
    op.create_index(
        op.f("ix_forum_replies_created_at"),
        "forum_replies",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forum_threads_created_at"),
        "forum_threads",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_video_quizzes_item_id"),
        "in_video_quizzes",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interactive_transcripts_item_id"),
        "interactive_transcripts",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invitations_expires_at"), "invitations", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_learning_items_lesson_id"),
        "learning_items",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_progresses_course_id"),
        "learning_progresses",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_progresses_user_id"),
        "learning_progresses",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lessons_week_module_id"), "lessons", ["week_module_id"], unique=False
    )
    op.alter_column(
        "payment_orders",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_payment_orders_target_id"),
        "payment_orders",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_transactions_vnp_transaction_no"),
        "payment_transactions",
        ["vnp_transaction_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_notes_item_id"), "personal_notes", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_matrices_bank_id"), "quiz_matrices", ["bank_id"], unique=False
    )
    op.drop_constraint(
        op.f("quiz_matrices_bank_id_fkey"), "quiz_matrices", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("quiz_matrices_bank_id_fkey"),
        "quiz_matrices",
        "question_banks",
        ["bank_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_users_enterprise_seat_key"),
        "users",
        ["enterprise_seat_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_week_modules_course_id"), "week_modules", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_weekly_deadlines_progress_id"),
        "weekly_deadlines",
        ["progress_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_weekly_deadlines_progress_id"), table_name="weekly_deadlines"
    )
    op.drop_index(op.f("ix_week_modules_course_id"), table_name="week_modules")
    op.drop_index(op.f("ix_users_enterprise_seat_key"), table_name="users")
    op.drop_constraint(
        op.f("quiz_matrices_bank_id_fkey"), "quiz_matrices", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("quiz_matrices_bank_id_fkey"),
        "quiz_matrices",
        "question_banks",
        ["bank_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_quiz_matrices_bank_id"), table_name="quiz_matrices")
    op.drop_index(op.f("ix_personal_notes_item_id"), table_name="personal_notes")
    op.drop_index(
        op.f("ix_payment_transactions_vnp_transaction_no"),
        table_name="payment_transactions",
    )
    op.drop_index(op.f("ix_payment_orders_target_id"), table_name="payment_orders")
    op.alter_column(
        "payment_orders",
        "amount",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_lessons_week_module_id"), table_name="lessons")
    op.drop_index(
        op.f("ix_learning_progresses_user_id"), table_name="learning_progresses"
    )
    op.drop_index(
        op.f("ix_learning_progresses_course_id"), table_name="learning_progresses"
    )
    op.drop_index(op.f("ix_learning_items_lesson_id"), table_name="learning_items")
    op.drop_index(op.f("ix_invitations_expires_at"), table_name="invitations")
    op.drop_index(
        op.f("ix_interactive_transcripts_item_id"), table_name="interactive_transcripts"
    )
    op.drop_index(op.f("ix_in_video_quizzes_item_id"), table_name="in_video_quizzes")
    op.drop_index(op.f("ix_forum_threads_created_at"), table_name="forum_threads")
    op.drop_index(op.f("ix_forum_replies_created_at"), table_name="forum_replies")
    op.alter_column(
        "courses",
        "price",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
        existing_server_default=sa.text("'1190000'::double precision"),
    )
    op.alter_column(
        "course_purchases",
        "amount",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
