"""add is_revoked revoked_reason to verified_certificates

Revision ID: 92c325e689de
Revises: 10ba27276f02
Create Date: 2026-07-24 14:09:17.102915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92c325e689de"
down_revision: Union[str, Sequence[str], None] = "10ba27276f02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verified_certificates",
        sa.Column(
            "is_revoked", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "verified_certificates",
        sa.Column(
            "revoked_reason", sa.Text(), nullable=False, server_default=sa.text("''")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verified_certificates", "revoked_reason")
    op.drop_column("verified_certificates", "is_revoked")
    # ### end Alembic commands ###
