"""Add enterprise licenses table

Revision ID: 972357a021b8
Revises: 41f8bbf03622
Create Date: 2026-07-22 07:37:20.277720

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "972357a021b8"
down_revision: str | Sequence[str] | None = "41f8bbf03622"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enterprise_licenses",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("partner_name", sa.String(length=255), nullable=False),
        sa.Column("total_seats", sa.Integer(), nullable=False),
        sa.Column("used_seats", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enterprise_licenses")
    # ### end Alembic commands ###
