"""add_order_index_to_lessons_and_learning_items

Revision ID: 9af0a523dbdb
Revises: 9116458c6c68
Create Date: 2026-07-25 12:43:07.179541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9af0a523dbdb"
down_revision: Union[str, Sequence[str], None] = "9116458c6c68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_items",
        sa.Column("order_index", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "lessons",
        sa.Column("order_index", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lessons", "order_index")
    op.drop_column("learning_items", "order_index")
    # ### end Alembic commands ###
