"""add_course_ownership_fields

Revision ID: a87b2367f1e6
Revises: 9af0a523dbdb
Create Date: 2026-07-25 17:03:07.952994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a87b2367f1e6"
down_revision: Union[str, Sequence[str], None] = "9af0a523dbdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column("owner_id", sa.String(length=64), nullable=False, server_default=""),
    )
    op.add_column(
        "courses",
        sa.Column(
            "co_instructor_ids",
            sa.ARRAY(sa.String(length=64)),
            nullable=False,
            server_default="{}",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "co_instructor_ids")
    op.drop_column("courses", "owner_id")
    # ### end Alembic commands ###
