"""refactor_pbac_single_identity

Revision ID: aaafb085b524
Revises: b72e59268d70
Create Date: 2026-08-02 16:51:47.717227

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaafb085b524"
down_revision: str | Sequence[str] | None = "b72e59268d70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_collaborators",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_id", "user_id", name="uq_course_collaborators_course_user"
        ),
    )
    op.create_index(
        op.f("ix_course_collaborators_course_id"),
        "course_collaborators",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_collaborators_user_id"),
        "course_collaborators",
        ["user_id"],
        unique=False,
    )
    op.drop_column("courses", "co_instructor_ids")
    op.execute("ALTER TABLE organization_roles ALTER COLUMN permissions DROP DEFAULT")
    op.execute(
        "ALTER TABLE organization_roles ALTER COLUMN permissions TYPE JSONB USING to_jsonb(permissions)"
    )
    op.execute(
        "ALTER TABLE organization_roles ALTER COLUMN permissions SET DEFAULT '[]'::jsonb"
    )
    op.drop_column("users", "system_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "system_role",
            sa.VARCHAR(length=11),
            server_default=sa.text("'USER'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "organization_roles",
        "permissions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(
            sa.JSON(), "sqlite"
        ),
        type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::character varying[]"),
    )
    op.add_column(
        "courses",
        sa.Column(
            "co_instructor_ids",
            postgresql.ARRAY(sa.VARCHAR(length=64)),
            server_default=sa.text("'{}'::character varying[]"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(
        op.f("ix_course_collaborators_user_id"), table_name="course_collaborators"
    )
    op.drop_index(
        op.f("ix_course_collaborators_course_id"), table_name="course_collaborators"
    )
    op.drop_table("course_collaborators")
    # ### end Alembic commands ###
