"""add last_reset_at to learning_progresses

Revision ID: bc379768993c
Revises: 38e60e429f76
Create Date: 2026-07-24 17:17:48.746548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc379768993c"
down_revision: Union[str, Sequence[str], None] = "7a8f9e1029ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_progresses",
        sa.Column("last_reset_at", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learning_progresses", "last_reset_at")
    # ### end Alembic commands ###
