"""remove_dead_user_item_completions_and_instructor_names_column

Revision ID: c773f6b0f9f7
Revises: f4639e60fd98
Create Date: 2026-08-08 16:27:13.295082

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c773f6b0f9f7"
down_revision: str | Sequence[str] | None = "f4639e60fd98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_item_completions_course_id"), table_name="user_item_completions"
    )
    op.drop_index(
        op.f("ix_user_item_completions_item_id"), table_name="user_item_completions"
    )
    op.drop_index(
        op.f("ix_user_item_completions_user_id"), table_name="user_item_completions"
    )
    op.drop_table("user_item_completions")
    op.drop_column("courses", "instructor_names")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column(
            "instructor_names",
            postgresql.ARRAY(sa.VARCHAR(length=128)),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table(
        "user_item_completions",
        sa.Column("id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "user_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "course_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "item_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "completed_at", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_item_completions_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "item_id",
            name=op.f("uq_user_item_completion"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_user_item_completions_user_id"),
        "user_item_completions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_item_completions_item_id"),
        "user_item_completions",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_item_completions_course_id"),
        "user_item_completions",
        ["course_id"],
        unique=False,
    )
    # ### end Alembic commands ###
