"""add_organization_and_role_models

Revision ID: d510ee603d61
Revises: b5a4c266f68e
Create Date: 2026-07-30 11:12:12.809101

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d510ee603d61"
down_revision: str | Sequence[str] | None = "b5a4c266f68e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )
    op.create_table(
        "organization_roles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("parent_role_id", sa.String(length=64), nullable=True),
        sa.Column(
            "permissions",
            sa.ARRAY(sa.String(length=100)),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_role_id"], ["organization_roles.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_roles_organization_id"),
        "organization_roles",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "organization_members",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("role_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="ACTIVE", nullable=False
        ),
        sa.Column("joined_at", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["organization_roles.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_members_organization_id"),
        "organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_members_user_id"),
        "organization_members",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "courses",
        sa.Column(
            "organization_id",
            sa.String(length=64),
            server_default="partner_community",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_courses_organization_id"), "courses", ["organization_id"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "system_role",
            sa.Enum("SUPER_ADMIN", "USER", name="systemrole", native_enum=False),
            server_default="USER",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "system_role")
    op.drop_index(op.f("ix_courses_organization_id"), table_name="courses")
    op.drop_column("courses", "organization_id")
    op.drop_index(
        op.f("ix_organization_members_user_id"), table_name="organization_members"
    )
    op.drop_index(
        op.f("ix_organization_members_organization_id"),
        table_name="organization_members",
    )
    op.drop_table("organization_members")
    op.drop_index(
        op.f("ix_organization_roles_organization_id"), table_name="organization_roles"
    )
    op.drop_table("organization_roles")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
