"""add_scope_type_and_allowed_course_ids_to_enterprise_licenses

Revision ID: e0b151c2d43e
Revises: 401a9bf0e06c
Create Date: 2026-07-29 21:34:53.714388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0b151c2d43e"
down_revision: Union[str, Sequence[str], None] = "401a9bf0e06c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enterprise_licenses",
        sa.Column(
            "scope_type",
            sa.String(length=32),
            server_default="ALL_COURSES",
            nullable=False,
        ),
    )
    op.add_column(
        "enterprise_licenses",
        sa.Column(
            "allowed_course_ids",
            sa.ARRAY(sa.String(length=64)),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("enterprise_licenses", "allowed_course_ids")
    op.drop_column("enterprise_licenses", "scope_type")
    # ### end Alembic commands ###
