"""add course_audit_logs table

Revision ID: e26aefbf2406
Revises: 7dbaed96d10a
Create Date: 2026-08-08 00:32:10.146270

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e26aefbf2406"
down_revision: str | Sequence[str] | None = "7dbaed96d10a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_audit_logs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("target_user_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_audit_logs_actor_id"),
        "course_audit_logs",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_audit_logs_course_id"),
        "course_audit_logs",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_audit_logs_target_user_id"),
        "course_audit_logs",
        ["target_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_course_audit_logs_target_user_id"), table_name="course_audit_logs"
    )
    op.drop_index(
        op.f("ix_course_audit_logs_course_id"), table_name="course_audit_logs"
    )
    op.drop_index(op.f("ix_course_audit_logs_actor_id"), table_name="course_audit_logs")
    op.drop_table("course_audit_logs")
    # ### end Alembic commands ###
