"""add_vnpay_orders_and_transactions

Revision ID: e2ad17d24d70
Revises: 7c42f9b108d1
Create Date: 2026-08-04 16:05:25.616426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2ad17d24d70"
down_revision: Union[str, Sequence[str], None] = "7c42f9b108d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partner_subscriptions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("partner_id", sa.String(length=64), nullable=False),
        sa.Column("plan_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("starts_at", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_partner_subscriptions_expires_at"),
        "partner_subscriptions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partner_subscriptions_partner_id"),
        "partner_subscriptions",
        ["partner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partner_subscriptions_user_id"),
        "partner_subscriptions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "payment_orders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("plan_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("vnp_txn_ref", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_orders_status"), "payment_orders", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_payment_orders_user_id"), "payment_orders", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_orders_vnp_txn_ref"),
        "payment_orders",
        ["vnp_txn_ref"],
        unique=True,
    )
    op.create_table(
        "payment_transactions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("vnp_transaction_no", sa.String(length=64), nullable=False),
        sa.Column("vnp_response_code", sa.String(length=16), nullable=False),
        sa.Column("vnp_bank_code", sa.String(length=32), nullable=False),
        sa.Column("vnp_pay_date", sa.String(length=32), nullable=False),
        sa.Column("raw_payload", sa.String(length=2048), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_transactions_order_id"),
        "payment_transactions",
        ["order_id"],
        unique=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.Enum(
            "USER_ROLE_UNSPECIFIED",
            "USER_ROLE_LEARNER",
            "USER_ROLE_INSTRUCTOR",
            "USER_ROLE_ADMIN",
            name="userrole",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.Enum(
            "USER_ROLE_UNSPECIFIED",
            "USER_ROLE_LEARNER",
            "USER_ROLE_INSTRUCTOR",
            "USER_ROLE_ADMIN",
            name="userrole",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_payment_transactions_order_id"), table_name="payment_transactions"
    )
    op.drop_table("payment_transactions")
    op.drop_index(op.f("ix_payment_orders_vnp_txn_ref"), table_name="payment_orders")
    op.drop_index(op.f("ix_payment_orders_user_id"), table_name="payment_orders")
    op.drop_index(op.f("ix_payment_orders_status"), table_name="payment_orders")
    op.drop_table("payment_orders")
    op.drop_index(
        op.f("ix_partner_subscriptions_user_id"), table_name="partner_subscriptions"
    )
    op.drop_index(
        op.f("ix_partner_subscriptions_partner_id"), table_name="partner_subscriptions"
    )
    op.drop_index(
        op.f("ix_partner_subscriptions_expires_at"), table_name="partner_subscriptions"
    )
    op.drop_table("partner_subscriptions")
    # ### end Alembic commands ###
