"""Initial baseline with partner module and V2 instructor signatures

Revision ID: e8ebc2975d4e
Revises: add_content_to_forum
Create Date: 2026-07-29 11:56:37.852857

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8ebc2975d4e"
down_revision: Union[str, Sequence[str], None] = "add_content_to_forum"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partners",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("logo_url", sa.String(length=512), nullable=False),
        sa.Column("banner_url", sa.String(length=512), nullable=False),
        sa.Column("website_url", sa.String(length=512), nullable=False),
        sa.Column("allowed_domains", sa.ARRAY(sa.String(length=255)), nullable=False),
        sa.Column("signature_image_url", sa.String(length=512), nullable=False),
        sa.Column("signer_name", sa.String(length=255), nullable=False),
        sa.Column("signer_title", sa.String(length=255), nullable=False),
        sa.Column("public_key_pem", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.String(length=64), nullable=False),
        sa.Column(
            "historical_public_keys",
            sa.ARRAY(sa.String(length=255)),
            nullable=False,
            server_default="{}",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )

    op.add_column(
        "users",
        sa.Column(
            "signature_image_url",
            sa.String(length=512),
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "users",
        sa.Column("title", sa.String(length=255), nullable=False, server_default=""),
    )
    op.add_column(
        "verified_certificates",
        sa.Column(
            "signer_name", sa.String(length=255), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "verified_certificates",
        sa.Column(
            "signer_title", sa.String(length=255), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "verified_certificates",
        sa.Column(
            "signature_image_url",
            sa.String(length=512),
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verified_certificates", "signature_image_url")
    op.drop_column("verified_certificates", "signer_title")
    op.drop_column("verified_certificates", "signer_name")
    op.drop_column("users", "title")
    op.drop_column("users", "signature_image_url")
    op.drop_table("partners")
    # ### end Alembic commands ###
