"""upgrade_jsonb_and_user_item_completions

Revision ID: f4639e60fd98
Revises: 0ca87f0df402
Create Date: 2026-08-08 01:05:13.698407

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4639e60fd98"
down_revision: str | Sequence[str] | None = "0ca87f0df402"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_item_completions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("completed_at", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "item_id", name="uq_user_item_completion"),
    )
    op.create_index(
        op.f("ix_user_item_completions_course_id"),
        "user_item_completions",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_item_completions_item_id"),
        "user_item_completions",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_item_completions_user_id"),
        "user_item_completions",
        ["user_id"],
        unique=False,
    )
    op.alter_column("learning_items", "test_cases_json", server_default=None)
    op.alter_column("learning_items", "rubric_criteria_json", server_default=None)
    op.alter_column(
        "learning_items",
        "test_cases_json",
        existing_type=sa.TEXT(),
        type_=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        existing_nullable=False,
        postgresql_using="CASE WHEN test_cases_json = '' OR test_cases_json IS NULL THEN '{}'::jsonb ELSE test_cases_json::jsonb END",
    )
    op.alter_column(
        "learning_items",
        "rubric_criteria_json",
        existing_type=sa.TEXT(),
        type_=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        existing_nullable=False,
        postgresql_using="CASE WHEN rubric_criteria_json = '' OR rubric_criteria_json IS NULL THEN '{}'::jsonb ELSE rubric_criteria_json::jsonb END",
    )
    op.alter_column(
        "peer_reviews",
        "rubric_criteria_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        existing_nullable=False,
        postgresql_using="rubric_criteria_json::jsonb",
    )
    op.alter_column(
        "quiz_active_sessions",
        "questions_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        existing_nullable=False,
        postgresql_using="questions_json::jsonb",
    )
    op.alter_column(
        "quiz_sessions",
        "questions_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        existing_nullable=False,
        postgresql_using="questions_json::jsonb",
    )
    op.alter_column(
        "verified_certificates",
        "open_badges_json_ld",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        existing_nullable=False,
        postgresql_using="open_badges_json_ld::jsonb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verified_certificates",
        "open_badges_json_ld",
        existing_type=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_sessions",
        "questions_json",
        existing_type=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_active_sessions",
        "questions_json",
        existing_type=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "peer_reviews",
        "rubric_criteria_json",
        existing_type=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "learning_items",
        "rubric_criteria_json",
        existing_type=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column(
        "learning_items",
        "test_cases_json",
        existing_type=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.drop_index(
        op.f("ix_user_item_completions_user_id"), table_name="user_item_completions"
    )
    op.drop_index(
        op.f("ix_user_item_completions_item_id"), table_name="user_item_completions"
    )
    op.drop_index(
        op.f("ix_user_item_completions_course_id"), table_name="user_item_completions"
    )
    op.drop_table("user_item_completions")
    # ### end Alembic commands ###
