"""migrate_partner_admin_to_org_owner

Revision ID: f7b500c09994
Revises: 480f9f14a872
Create Date: 2026-07-31 00:29:38.960553

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7b500c09994"
down_revision: str | Sequence[str] | None = "480f9f14a872"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=13),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.execute("UPDATE users SET role = 'USER_ROLE_LEARNER' WHERE role = 'LEARNER'")
    op.execute(
        "UPDATE users SET role = 'USER_ROLE_INSTRUCTOR' WHERE role IN ('INSTRUCTOR', 'PARTNER_ADMIN', 'USER_ROLE_PARTNER_ADMIN')"
    )
    op.execute("UPDATE users SET role = 'USER_ROLE_TA' WHERE role = 'TA'")
    op.execute(
        "UPDATE users SET role = 'USER_ROLE_SUPER_ADMIN' WHERE role = 'SUPER_ADMIN'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(length=64),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
