"""add_unique_constraint_to_course_reviews

Revision ID: fd77c3cd6a9a
Revises: bc379768993c
Create Date: 2026-07-24 22:02:49.449026

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd77c3cd6a9a"
down_revision: str | Sequence[str] | None = "bc379768993c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_course_reviews_user_course", "course_reviews", ["user_id", "course_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_course_reviews_user_course", "course_reviews", type_="unique"
    )
    # ### end Alembic commands ###
