"""add_subject_level_to_courses

Revision ID: ff858aa2ba07
Revises: 55863ba0dee5
Create Date: 2026-07-25 15:15:24.180158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff858aa2ba07"
down_revision: Union[str, Sequence[str], None] = "55863ba0dee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column(
            "subject",
            sa.String(length=64),
            server_default="UNSPECIFIED",
            nullable=False,
        ),
    )
    op.add_column(
        "courses",
        sa.Column(
            "level", sa.String(length=32), server_default="UNSPECIFIED", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "level")
    op.drop_column("courses", "subject")
    # ### end Alembic commands ###
