"""Domain constants for the Catalog bounded context."""

DEFAULT_ENTERPRISE_KEY_TOTAL_SEATS: int = 500

MIN_RATING_STARS: int = 1
MAX_RATING_STARS: int = 5
MAX_REVIEW_COMMENT_LENGTH: int = 2000
MIN_PROGRESS_PERCENT_FOR_REVIEW: float = 50.0
VERIFIED_COMPLETER_PROGRESS_PERCENT: float = 100.0
