"""Domain constants for the Identity bounded context."""

DEFAULT_ENTERPRISE_KEY_TOTAL_SEATS: int = 500
DEFAULT_PBKDF2_ITERATIONS: int = 100000
ENTERPRISE_REVOCATION_GRACE_PERIOD_DAYS: int = 30
ENTERPRISE_REVOCATION_MAX_PROGRESS_PERCENT: float = 20.0

INTERNAL_SYSTEM_ORG_ID: str = "partner_community"
INTERNAL_SYSTEM_ORG_SLUG: str = "coursera-project-network"
INTERNAL_SYSTEM_ORG_NAME: str = "Coursera Project Network"
INSTRUCTOR_APPLICATION_REAPPLY_COOLDOWN_DAYS: int = 14

DEFAULT_INVITATION_EXPIRATION_DAYS: int = 7
INVITATION_TOKEN_BYTE_LENGTH: int = 32

# Password Policy
PASSWORD_MIN_LENGTH: int = 6
LOGIN_MAX_ATTEMPTS: int = 5
LOGIN_LOCKOUT_SECONDS: int = 900  # 15 phút
