"""Domain constants for the Identity bounded context."""

DEFAULT_ENTERPRISE_KEY_TOTAL_SEATS: int = 500
DEFAULT_PBKDF2_ITERATIONS: int = 100000
ENTERPRISE_REVOCATION_GRACE_PERIOD_DAYS: int = 30
ENTERPRISE_REVOCATION_MAX_PROGRESS_PERCENT: float = 20.0
