from typing import Any, Protocol

from src.modules.identity.domain.entities import (
    EnterpriseLicense,
    InstructorApplication,
    Invitation,
    Organization,
    OrganizationMember,
    User,
)


class IIdentityRepository(Protocol):
    async def get_by_id(self, user_id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_google_id(self, google_id: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def recycle_enterprise_seat(self, seat_key: str) -> None: ...
    async def get_enterprise_license(self, key: str) -> EnterpriseLicense | None: ...
    async def increment_enterprise_seat(self, key: str) -> bool: ...
    async def decrement_enterprise_seat(self, key: str) -> bool: ...


class IEnterpriseLicenseRepository(Protocol):
    async def get_by_key(self, key: str) -> EnterpriseLicense | None: ...
    async def list_licenses(
        self, partner_name: str = ""
    ) -> list[EnterpriseLicense]: ...
    async def create_license(
        self, license_entity: EnterpriseLicense
    ) -> EnterpriseLicense: ...
    async def increment_enterprise_seat(self, key: str) -> bool: ...
    async def decrement_enterprise_seat(self, key: str) -> bool: ...


class IOrganizationRepository(Protocol):
    async def get_organization_by_id(self, org_id: str) -> Organization | None: ...
    async def save_organization(self, org: Organization) -> Organization: ...
    async def add_member(
        self,
        user_id: str,
        org_id: str,
        role_id: str = "INSTRUCTOR",
        status: str = "ACTIVE",
    ) -> OrganizationMember: ...
    async def get_member(
        self, user_id: str, org_id: str
    ) -> OrganizationMember | None: ...
    async def remove_member(self, user_id: str, org_id: str) -> bool: ...
    async def list_members_with_details(self, org_id: str) -> list[dict[str, Any]]: ...
    async def list_user_organizations(self, user_id: str) -> list[Organization]: ...
    async def list_user_organization_details(
        self, user_id: str
    ) -> list[dict[str, Any]]: ...
    async def create_audit_log(
        self,
        org_id: str,
        actor_id: str,
        target_user_id: str,
        action: str,
        details: str = "",
    ) -> dict[str, Any]: ...
    async def list_audit_logs(self, org_id: str) -> list[dict[str, Any]]: ...


class IInstructorApplicationRepository(Protocol):
    async def get_by_id(self, application_id: str) -> InstructorApplication | None: ...
    async def get_latest_by_user_id(
        self, user_id: str
    ) -> InstructorApplication | None: ...
    async def list_applications(
        self, status_filter: str = ""
    ) -> list[InstructorApplication]: ...
    async def save(
        self, application: InstructorApplication
    ) -> InstructorApplication: ...


class IInvitationRepository(Protocol):
    async def save(self, invitation: Invitation) -> Invitation: ...
    async def get_by_id(self, invitation_id: str) -> Invitation | None: ...
    async def get_by_token_hash(self, token_hash: str) -> Invitation | None: ...
    async def find_pending_invitation(
        self, email: str, target_id: str, inv_type: str
    ) -> Invitation | None: ...
    async def list_invitations_for_user(
        self, email: str, status_filter: str = ""
    ) -> list[Invitation]: ...
    async def list_invitations_for_target(
        self, target_id: str, status_filter: str = ""
    ) -> list[Invitation]: ...
